### ISSUE TITLE
`findById` and `findByName` and `findFirst` methods

### ISSUE THREAD

**Issue by galmail** [ExtraHorizon/javascript-sdk#203]
In order to simplify the usage, we want to add `findById` and `findByName` and `findFirst` to all services which offer a `find` method using RQL.

**Comment by jensdev** [comment]
How should we approach this. At the moment all calls that receive rql, receive the `build()` result, which returns a `RQLString`. 

Should the rqlBuilder be able to call with an already existing `rql`.
```ts
const rql = rqlBuilder().limit(10).build();
// rql = `?limit(10)`
rqlBuilder(rql).eq('id',id).build();
// ?limit(10)&id('id',id)
```

Do we want to filter out other rql which would limit the results when you are calling `findById` or `findByName`.  And only allow certain options like `select` 
```ts
const rql = rqlBuilder().eq('id',id).build();
sdk.data.schemas.findByName('test', rql);
// rql sent to the backend is `?eq('id',id)&eq('name', 'test')
```

Or do we add another approach where you can pass in an object to the rqlBuilder. See https://www.npmjs.com/package/javascript-rql for more inspiration. This way the value stored in the rqlBuilder could be an object in stead of a string. We could then also add a function to parse an `RQLString` which is passed in the to `findByName` and add the `eq('name',name)` 
```ts
const rql = rqlBuilder({ $eq: { id }, select: }).build();
```

**Comment by ThomasReyskens** [comment]
I would make the rqlBuilder take a parsed rql string in the function call like you proposed here: `rqlBuilder(rql).eq('id',id).build();` I would also not limit the functionallity of the incoming rql. This is the responsibility of the user imo. When the passed and the incoming rql have the same parameters, I would trigger a console log, indicating that you passed the same parameters. The incoming will overwrite the passed then

**Comment by ThomasReyskens** [comment]
I also prefer our way of handling and creating the rql over the javascript-rql!
