### ISSUE TITLE
update readme to reflect the correct usage of types

### ISSUE THREAD

**Issue by galmail** [ExtraHorizon/javascript-sdk#215]
Since destructuring types does not work in Typescript for some reason, the correct usage should be:

```
const schema: DataServicesTypes.Schema = schemas.data[0];
```

instead of:

```
import type { DataServicesTypes: { Schema,
  DocumentBase,
  JSONSchemaObject,
  JSONSchemaArray,
  JSONSchemaNumber } }  from "@extrahorizon/javascript-sdk";
```

See https://fibricheck.slack.com/archives/C01SQCU2MNU/p1622727658003100?thread_ts=1622726767.001800&cid=C01SQCU2MNU

**Comment by jensdev** [comment]
I'll close this because all naming conflicts are resolved now, so you should be able to import directly from the package
```ts
import type { Schema, DocumentBase, JSONSchemaObject, JSONSchemaArray, JSONSchemaNumber }  from "@extrahorizon/javascript-sdk";
```
