### ISSUE TITLE
For BE: Service discovery service

### ISSUE THREAD

**Issue by edwwaarrdd** [ExtraHorizon/javascript-sdk#264]
Services are on different ports normally automatically done by gateway.
But in the microservices cluster we need to override the IP address and port.
So user service with version X should connect to ip-address XYZ on port X
Add an option to overwrite service endpoints
Add an option to overwrite authentication

**Comment by jensdev** [comment]
```ts
import { createClient } from "@extrahorizon/javascript-sdk";

const sdk = createClient({
  microservices: true,
  serviceUrls: {
    users: 'http://192.168.1.20:3000',
    data: 'http://192.168.1.21:3000'
  }
});

await sdk.auth.authenticate({
  secret: 'very-secret-string'
});
```

We could also have a different name like `createInternalClient` ? 
The `secret` can be used to retrieve tokens or is it just added to the headers?

**Comment by jensdev** [comment]
import { createClient } from "@extrahorizon/javascript-sdk";
```ts
export interface ServiceLocatorInfo {
  service: string;
  version?: string;
}
export interface ServiceLocation {
  host: string;
  port: number;
}
const sdk = createClient({
  microservices: true,
  serviceUrlFn: (service: ServiceLocatorInfo):ServiceLocation  => {
    return ServiceUrls[service]
  }
});

await sdk.auth.authenticate({
  secret: 'very-secret-string'
});
```

**Comment by KobeLeysen** [comment]
> ```ts
> import { createClient } from "@extrahorizon/javascript-sdk";
> 
> const sdk = createClient({
>   microservices: true,
>   serviceUrls: {
>     users: 'http://192.168.1.20:3000',
>     data: 'http://192.168.1.21:3000'
>   }
> });
> 
> await sdk.auth.authenticate({
>   secret: 'very-secret-string'
> });
> ```
> 

> We could also have a different name like `createInternalClient` ?
> The `secret` can be used to retrieve tokens or is it just added to the headers?

@jensdev I understand the proposal. But the issue is that services can change from IP and Port very frequently. When you would do it this way the IP and port number are provided to the SDK on initialization and startup of the microservice.

**Comment by KobeLeysen** [comment]
> import { createClient } from "@extrahorizon/javascript-sdk";
> 
> ```ts
> export interface ServiceLocatorInfo {
>   service: string;
>   version?: string;
> }
> export interface ServiceLocation {
>   host: string;
>   port: number;
> }
> const sdk = createClient({
>   microservices: true,
>   serviceUrlFn: (service: ServiceLocatorInfo):ServiceLocation  => {
>     return ServiceUrls[service]
>   }
> });
> 
> await sdk.auth.authenticate({
>   secret: 'very-secret-string'
> });
> ```

@jensdev this would indeed be the way to go
