### ISSUE TITLE
404 Not Found - GET https://registry.npmjs.org/@extrahorizon%2fjavascript-sdk

### ISSUE THREAD

**Issue by ankitnetsol** [ExtraHorizon/javascript-sdk#313]
Hello,

  When I am installing the @extrahorizon/javascript-sdk package using npm install @extrahorizon/javascript-sdk command I am getting  404 not found error (404 Not Found - GET https://registry.npmjs.org/@extrahorizon%2fjavascript-sdk - Not found). So please guide me regarding this error. 
  
  I am using the below version of node and npm. (Node - v10.19.0, npm - 6.14.4).

Thanks.

**Comment by edwwaarrdd** [comment]
Yes also see #311 with some extra explanation

**Comment by ankitnetsol** [comment]
@galmail @edwwaarrdd Still getting the same error. when I am open https://registry.npmjs.org/@extrahorizon%2fjavascript-sdk link in the browser I am getting not found error.

**Comment by edwwaarrdd** [comment]
@ankitnetsol 
This is correct, the package is not hosted on the NPMJS registry but on the GitHub registry https://github.com/ExtraHorizon/javascript-sdk/packages/702908?version=4.0.0

We have updated the installation instructions https://github.com/ExtraHorizon/javascript-sdk#installation
Can you follow these and then try again?

**Comment by ankitnetsol** [comment]
@edwwaarrdd I am trying your solution but not working. Please guide me to another solution.
