### ISSUE TITLE
Add support for confidential oauth2.0 applications

### ISSUE THREAD

**Issue by KobeLeysen** [ExtraHorizon/javascript-sdk#340]
Currently there is no option for authentication the sdk with confidential applications and using the clientSecret.

**Comment by edwwaarrdd** [comment]
I think this is maybe also tackled in #328

**Comment by jensdev** [comment]
```ts
const sdk = createMicroservicesClient({
  host: "",
});

await sdk.auth.authenticate({
  secret: "secret-string",
});
```

It just add the `secret` on the headers

```ts
httpWithAuth.interceptors.request.use(
  async (config: AxiosRequestConfig): Promise<AxiosRequestConfig> => {
    const [_, service, version] = config.url.split('/');
    const { host, port } = await options.serviceUrlFn({ service, version });
    return {
      ...config,
      headers: { ...config.headers, 'X-secret': authConfig.secret },
      baseURL: `${host}:${port}`,
    };
  }
);
```

**Comment by jensdev** [comment]
- https://darutk.medium.com/oauth-2-0-client-authentication-4b5f929305d4
- https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1

**Comment by jensdev** [comment]
Could you give me some more details on how this is supposed to work?
Is there a different grant_type? 
I keep getting 
```
{
    "error": "invalid_client",
    "description": "Client credentials are missing in request"
}
```

I'm putting the `client_secret` next to the `client_id` on the request body
