### ISSUE TITLE
Invalid type for `tag` in `FileService.create`

### ISSUE THREAD

**Issue by xlambein** [ExtraHorizon/javascript-sdk#352]
## Description

The `tag` field in `FileService.create` has type `[]`, which is the empty tuple, instead of `string[]`.  As a result, writing the following code:

```typescript
const tags = ['foo', 'bar'];
await sdk.files.create(name, file, { tags })
```

produces the error:

```
Type 'string[]' is not assignable to type '[]'.
  Target allows only 0 element(s) but source may have more.ts(2322)
```

Here are the locations in the source code, for the interface:

https://github.com/ExtraHorizon/javascript-sdk/blob/46472027b38eeee291e0d65a272a4539bae24e9d/src/services/files/types.ts#L95

and for the actual implementation:

https://github.com/ExtraHorizon/javascript-sdk/blob/46472027b38eeee291e0d65a272a4539bae24e9d/src/services/files/files.ts#L50

## Specifications

- Version: `4.2.0`

**Comment by jensdev** [comment]
Closed via #353
