### ISSUE TITLE
Missing Sender_id on sending notification

### ISSUE THREAD

**Issue by PieterFdx** [ExtraHorizon/javascript-sdk#396]
![Schermafbeelding 2021-09-09 190447](https://user-images.githubusercontent.com/63776001/133042675-bc21d743-8f9b-4677-9bac-eb219b078e80.png)
## Description
Creating a notification returns a MISSING_REQUIRED_FIELD_EXCEPTION off the api, sender_id fields is necessary (check screenshot)

## Steps to Reproduce
1. Try to send/create a notification
1. 
1.

## Code example

await sdk.notifications.create()

## Specifications

- Version: latest
- Platform: Windows
- Endpoint or service affected: notifications

**Comment by jensdev** [comment]
@PieterFdx thanks for reporting this. How are you initializing the SDK and authenticating?  The SDK will set the `sender_id` to the userId from the response of the last token data.

**Comment by PieterFdx** [comment]
![afbeelding](https://user-images.githubusercontent.com/63776001/133059446-2c39446a-ce71-4a79-b3c7-db380ae0f03c.png)

I do this for authentication
