### ISSUE TITLE
Error while trying to use Javascript SDK in existing export script that was using our old Api Client

### ISSUE THREAD

**Issue by allardke** [ExtraHorizon/javascript-sdk#406]
## Description

node_modules/@extrahorizon/javascript-sdk/build/types/services/files/types.d.ts:75:40 - error TS2304: Cannot find name 'Blob'.

75     create(fileName: string, fileData: Blob | Buffer | ReadStream, options?: OptionsBase & {
~~~~

Found 1 error.

You can ask Jonas Allard for a ZIP file of the export script where the error occurs.

## Steps to Reproduce
/

## Code example
/

```typescript

```

## Specifications

- Version: 3.1.0
- Platform: /
- Endpoint or service affected: /

**Comment by jensdev** [comment]
This was resolved by bumping `@types/node` to a `16.x.x` version.
But it was also resolved by edits to the tsconfig.json. Removed the `lib` option which was set to `["es7" ]`
