### ISSUE TITLE
List all objects for the provided rql query

### ISSUE THREAD

**Issue by allardke** [ExtraHorizon/javascript-sdk#407]
## What do you want to achieve?

Add the possibility to fetch all objects for the provided rql query for the following services / endpoints:

* tasks
* templates
* payments: products, orders, subscription entitlements, appstore subscriptions, stripe users
* profiles

**Comment by jensdev** [comment]
- [x] tasks
- [x] templates
- payments
  - [x] orders
  - [x] products
  - [ ] subscription entitlements
  - [ ] appstore subscriptions
  - [ ] stripe users  
- profiles
  - [x] profiles
  - [x] loogs 
- [x] profile logs
