### ISSUE TITLE
MFA management functions are not yet supported

### ISSUE THREAD

**Issue by KobeLeysen** [ExtraHorizon/javascript-sdk#464]
[Mfa functions are currently not supported](https://developers.extrahorizon.io/swagger-ui/?url=https://developers.extrahorizon.io/services/auth-service/2.0.4-dev/openapi.yaml#/MFA)

- Retrieving MFA settings
- enabling MFA
- disabling MFA
- adding MFA method
- Confirming an MFA method
- removing an MFA method

**Comment by jensdev** [comment]
Hmm. They should be under `sdk.auth.users`
https://github.com/ExtraHorizon/javascript-sdk/blob/dev/src/services/auth/users.ts

- Retrieving MFA settings -> `sdk.auth.users.getMfaSetting`
- enabling MFA -> `sdk.auth.users.enableMfa`
- disabling MFA -> ` sdk.auth.users.disableMfa`
- adding MFA method -> `sdk.auth.users.addMfaMethod`
- Confirming an MFA method -> `sdk.auth.users.confirmMfaMethodVerification`
- removing an MFA method -> `sdk.auth.users.removeMfaMethod`

Was something recently changed or any bugs related to the calls?
