### ISSUE TITLE
oauth1 token management is not supported

### ISSUE THREAD

**Issue by KobeLeysen** [ExtraHorizon/javascript-sdk#465]
[oauth1 functions are not supported](https://developers.extrahorizon.io/swagger-ui/?url=https://developers.extrahorizon.io/services/auth-service/2.0.4-dev/openapi.yaml#/OAuth1)

- retrieving list of oauth1 tokens
- removing an oauth1 token
- generating sso tokens
- consuming sso tokens

**Comment by jensdev** [comment]
Already exist
- generating sso tokens -> `sdk.auth.oauth1.generateSsoToken` 
- consuming sso tokens -> `sdk.auth.oauth1.consumeSsoToken` 

Will be added in next version
- retrieving list of oauth1 tokens
- removing an oauth1 token
