### ISSUE TITLE
Confirm presence is not supported

### ISSUE THREAD

**Issue by KobeLeysen** [ExtraHorizon/javascript-sdk#466]
[confirm presence is not supported](https://developers.extrahorizon.io/swagger-ui/?url=https://developers.extrahorizon.io/services/auth-service/2.0.4-dev/openapi.yaml#/Confirm%20presence)

**Comment by jensdev** [comment]
It's under `sdk.auth.confirmPresence`
https://github.com/ExtraHorizon/javascript-sdk/blob/dev/src/services/auth/index.ts#L32
