### ISSUE TITLE
Full schema sync functionality

### ISSUE THREAD

**Issue by KobeLeysen** [ExtraHorizon/javascript-sdk#467]
Add functionality to the SDK to submit a full json schema and the SDK will try to update/synchronize it with the ExH backend.

**Comment by KobeLeysen** [comment]
Take a look at the current schema-sync-tool for input

**Comment by FilipAben** [comment]
Still necessary since this is in exh-cli now?

**Comment by wwaaijer-exh** [comment]
Indeed, the Extra Horizon CLI should be used for this.
Docs: https://docs.extrahorizon.com/cli
