### ISSUE TITLE
Support for fetching credentials from `~/.exh` folder

### ISSUE THREAD

**Issue by christopherhex** [ExtraHorizon/javascript-sdk#538]
## What do you want to achieve?

For the Extra Horizon CLI, the credentials can be stored in a similar way to the AWS cli: in `~/.exh` . Would be very useful if the SDK is able to fetch the credentials in the same place as the CLI. 

See also here: https://docs.extrahorizon.com/cli/setup/credentials

**Comment by jensdev** [comment]
For more info see https://extrahorizon.github.io/javascript-sdk/#/docs/examples/authentication?id=snippet-for-stored-credentials
