### ISSUE TITLE
Update Application / ApplicationVersion types

### ISSUE THREAD

**Issue by jensdev** [ExtraHorizon/javascript-sdk#551]
Use type narrowing to return better types.
@ThomasReyskens could you add your code snippet?

**Comment by ThomasReyskens** [comment]
`  const app = await sdk.auth.applications.create({
    name: "hey",
    description: "hallo",
    type: 'oauth1'
  });

  const version = await sdk.auth.applications.createVersion(app.id, {name: '1.0.0'});

  app.versions.push(version);`

**Comment by ThomasReyskens** [comment]
proposed solution: 

```javascript
const version = await sdk.auth.applications.createVersion(app.id, {type: 'oauth1', name: '1.0.0'});
```

**Comment by jensdev** [comment]
- [ ] affectedRecords return type on update
- [ ] typeguards in README ( auth )
- [ ] expose types

**Comment by jensdev** [comment]
https://docs.extrahorizon.com/javascript-sdk/examples/authentication#typeguards
