### ISSUE TITLE
Not able to use auth.login() in a webpage with the 'createProxyClient'

### ISSUE THREAD

**Issue by allardjonas** [ExtraHorizon/javascript-sdk#594]
```
import { createProxyClient } from '@extrahorizon/javascript-sdk';
import { url } from '@fibricheck/pages-helper-utils';

export const sdk = createProxyClient({ host: url.apx });
```

what we want to achieve:

await sdk.auth.login(email, password);

the sdk should use the login endpoint of the Admin Proxy Server to set the fibproxy cookie.

const baseUrl = process.env.REACT_APP_TARGET_HOST;

=> apx.dev.fibricheck.com

export const endpoint = {
  login: `${baseUrl}/login`,
  logout: `${baseUrl}/logout`,
  loginMfa: `${baseUrl}/login/mfa`,
};

  const body: any = {
    email: this.state.email,
    password: this.state.password,
  };
     
const login = await apx.post(apx.endpoint.login, '', body);

**Comment by FilipAben** [comment]
I guess we should use `authenticate` iso `login` to remain a bit consistent with the other clients?
