### ISSUE TITLE
Improve parameters for the RQL contains operator 

### ISSUE THREAD

**Issue by AaronTrippaers** [ExtraHorizon/javascript-sdk#603]
## What do I want to achieve?

Change the RQL function signature of contains to and execute the and function on the list:
```
contains: (field: string, ...list: RQLString[]) => RQLBuilder;
```
### Why is it better? 

- The `and` is always needed when providing an expression. If only one check is performed the contains operator can be easily removed.
```
// Following operation:
.contains("data",rqlBuilder().gt("heartrate", "60").intermediate())
// Can be replaced with:
gt("data.heartrate","60")
```
- The function signature above makes it in my opinion more clear that the checks have to be given separately and that the following code won't work.
```
.contains("data",rqlBuilder().gt("heartrate", "60").lt("heartrate", "90").intermediate())
```
- It makes the code more concise and readable by removing the `and` function and its `intermediate` call. See the difference between the 2 examples below. 

Before:
```
.contains(
    "data",
    rqlBuilder().and(
            rqlBuilder().gt("heartrate", "60").intermediate(),
            rqlBuilder().lt("heartrate", "90").intermediate()
    ).intermediate()
)
```

After: 

```
.contains(
    "data",
    rqlBuilder().gt("heartrate", "60").intermediate(),
    rqlBuilder().lt("heartrate", "90").intermediate()
)
```

**Comment by FilipAben** [comment]
I agree it would be better, as long as it's done in a way that it doesn't break existing applications. 

So 
```
.contains(
    "data",
    rqlBuilder().and(
            rqlBuilder().gt("heartrate", "60").intermediate(),
            rqlBuilder().lt("heartrate", "90").intermediate()
    ).intermediate()
)
```
should still work fine

**Comment by AaronTrippaers** [comment]
@FilipAben I have a proposal PR here: https://github.com/ExtraHorizon/javascript-sdk/pull/604. It still supports the example you gave. The url will just contain an unnecessary but not breaking `and` statement as you can see below: 
```
?contains(and(and(gt(heartrate,60),lt(heartrate,60))))
```
