### ISSUE TITLE
Add possibility to unzip a file from the fileservice

### ISSUE THREAD

**Issue by ThomasReyskens** [ExtraHorizon/javascript-sdk#611]
## What do you want to achieve?
Now, you get the bytestream from the fileservice. It would be nice if the SDK had a build in unzip function

**Comment by FilipAben** [comment]
Not sure. If all files in the file service would be mandatory zip-files, then for sure. But otherwise it doesn't feel like it belongs there and adds to bloat of the SDK.

**Comment by wwaaijer-exh** [comment]
We've added some upload/download examples to the docs here:
https://docs.extrahorizon.com/javascript-sdk/features/files

I know this doesn't cover unzipping, but it gives more clarity about what does/doesn't happen in the sdk.
If we would cover unzipping, we would also "need" to cover zipping which, like Filip mentions, feels a bit off.
