### ISSUE TITLE
SDK spits out minified code upon errors/exceptions

### ISSUE THREAD

**Issue by FilipAben** [ExtraHorizon/javascript-sdk#678]
When there's an error, the SDK occasionally spits out its minified code, which is so big you can't really see the error.
In some external logging systems the output is even cut off so you don't see any error at all.

**Comment by robinclaes** [comment]
https://github.com/mantinedev/mantine does a good job at this (including sourcemaps) - might be worth looking at as an example.

**Comment by wwaaijer-fib** [comment]
Maybe I'm going to say something really stupid here, but do we need to minify?
Seems to me that the tooling of the projects using the sdk are doing that if they need to.
Or is that not how those tools work and all packages should be shipped minified? 😬

**Comment by ThomasReyskens** [comment]
rollup produces ESM code that is easily tree-shakeable, so I would so no!

**Comment by ThomasReyskens** [comment]
Also can't trace these issues in sentry because it is minified

**Comment by wwaaijer-exh** [comment]
Fixed in `8.4.1`
