### ISSUE TITLE
Code style and quality assurance workflows are not a dependency for the publish workflow for the master build

### ISSUE THREAD

**Issue by wwaaijer-exh** [ExtraHorizon/javascript-sdk#695]
All workflows run in parallel instead of depending on each other. Not so much of a problem for dev builds, but a failure in either the "code style" or "quality assurance" workflows should prevent the package from being published.

**Comment by SalinaExh** [comment]
https://extrahorizon.atlassian.net/browse/SVCS-447

**Comment by wwaaijer-exh** [comment]
Fixed in v8.1.0
