### ISSUE TITLE
the data.documents.unlinkGroups does not have the possibility to provide no groupid's

### ISSUE THREAD

**Issue by ThomasReyskens** [ExtraHorizon/javascript-sdk#698]
## Description
I want to unlink all groups, but this requires an empty object. Currently, this is not possible because this is not optional. -> `unlinkGroups(schemaId: string, documentId: string, requestBody: {  groupIds: string[] };`

simply changing this to 
`unlinkGroups(schemaId: string, documentId: string, requestBody: {  groupIds: string[] } | {};` should suffice I guess!

**Comment by wwaaijer-exh** [comment]
Fixed in `8.2.0`
