### ISSUE TITLE
Casing issue

### ISSUE THREAD

**Issue by ThomasReyskens** [ExtraHorizon/javascript-sdk#712]
## Description
Some calls still require a payload in snake_case, but the SDK converts everything to camelCase.
A solution can be to add a parameter to leave the casing?

**Comment by SalinaExh** [comment]
Jira: https://extrahorizon.atlassian.net/browse/SVCS-445

**Comment by wwaaijer-exh** [comment]
Was fixed in v8.0.0 with the `normalizeCustomData` feature
