### ISSUE TITLE
data service api call documentation not indicating that it is also possible to use a schema name iso a schema id

### ISSUE THREAD

**Issue by allardjonas** [ExtraHorizon/javascript-sdk#713]
## Description

<img width="987" alt="Schermafbeelding 2023-01-03 om 10 31 06" src="https://user-images.githubusercontent.com/94392335/210331683-ac51e3be-f081-4682-bb30-6533c1579c07.png">

## Steps to Reproduced
1.
1.
1.

## Code example

```typescript

```

## Specifications

- Version:
- Platform:
- Endpoint or service affected:

**Comment by SalinaExh** [comment]
Jira: https://extrahorizon.atlassian.net/browse/SVCS-444

**Comment by wwaaijer-exh** [comment]
The parameter name `schemaId` shown in the screenshot should be changed to `schemaIdOrName` as both are supported to be supplied there

**Comment by wwaaijer-exh** [comment]
Fixed in `8.2.0`
