### ISSUE TITLE
Permission VIEW_SUBSCRIPTION_ENTITLEMENTS missing from GlobalPermissionName

### ISSUE THREAD

**Issue by arnedubois** [ExtraHorizon/javascript-sdk#726]
## Description
The permission VIEW_SUBSCRIPTION_ENTITLEMENTS is missing from `GlobalPermissionName` enum. Additionally, `parseGlobalPermission(permissions: string[])` should not return undefined when an input is not a GlobalPermissionName. Either throw an exception or return the input string so that the server can handle the error.

Since missing GlobalPermissionName is a recurring bug, we should allow the functions `addPermission` and `removePermission` to accept an array of strings. This ensures that workflows using these functionalities won't throw an error when a missing permission is encountered.

## Steps to Reproduce
1. Call parseGlobalPermissions(['VIEW_SUBSCRIPTION_ENTITLEMENTS'])
2. Warning is displayed and undefined is returned

## Code example

```typescript
const permissions = parseGlobalPermissions(['VIEW_SUBSCRIPTION_ENTITLEMENTS']);
```

**Comment by SalinaExh** [comment]
Jira: https://extrahorizon.atlassian.net/browse/SVCS-443

**Comment by wwaaijer-exh** [comment]
Will be fixed by: https://github.com/ExtraHorizon/javascript-sdk/issues/784
