### ISSUE TITLE
UserData type misses optionals for data

### ISSUE THREAD

**Issue by MilenkaDerumeauxCZ** [ExtraHorizon/javascript-sdk#734]
## Description
The `me` endpoint (`sdk.users.me()`) returns the `User`/`UserData` type. In this interface, there are no optionals, even though several properties are potentially undefined.

Properties that can be undefined: (from my experience)
- patientEnlistments
- staffEnlistments
- roles
- profileImage

## Steps to Reproduce
1. Create a user with patientEnlistments
2. Fetch with `me` endpoint
3. Try to log a missing property: `user.staffEnlistments.length` -> error

## Code example

```typescript
const user = await sdk.users.me();
console.log(user.staffEnlistments.length);
```

## Specifications

- Version: `^7.2.0`
- Endpoint or service affected: `me`

**Comment by wwaaijer-exh** [comment]
Fixed in `8.2.0`
